hw1
FlufyUnicorn/kts-front-summer-2021 pull request #1
Opened 2021-08-22 10:19 UTC by FlufyUnicorn

2021-08-22 20:58 UTC, n-merkulova requested changes
С возвращением на курс фронтенда! Круто, что ты сделала сразу на реакте и справилась со второй частью ДЗ, но все же есть некоторые недочеты, которые лучше поправить)

2021-08-22 20:58 UTC, n-merkulova commented on src/App.tsx
> +import MainPage from "./components/MainPage/MainPage";
Если это страница, то лучше положить ее в папку pages. А еще здорово бы сделать дефолтный экспорт из MainPage/index.ts

2021-08-22 20:58 UTC, n-merkulova commented on src/App.tsx
> +import MainPage from "./components/MainPage/MainPage";
Еще обрати внимание, что для того, чтобы не было проблем с код-стайлом (например, то одинарные кавычки в импортах, то двойные), можно хотя бы [prettier](https://prettier.io/) подключить

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.css
> +    font-weight: normal;
Для чего эти свойства со значениями normal? Они точно нужны?

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.css
> +    margin-bottom: 4px;
Можно использовать сокращенную запись для margin

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.css
> +    display: inline;
А будут работать свойства width и height при свойстве display: inline? Оно здесь вообще нужно?

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.css
> +    align-items: center;
А зачем здесь свойство align-items?

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.css
> +    display: inline;
Опять же, почему здесь display: inline?

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.css
> +    vertical-align: -16%;
Немного странный подгон. А почему бы не vertical-align: middle? Вообще, вероятно, удобно было бы просто search сделать flex-контейнером

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.css
> +    background: var(--colorDisabled);
Можно было бы добавить свойство transition для более плавных переходов

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.tsx
> +                <input placeholder = 'Введите название организации'></input>
`<input />`

2021-08-22 20:58 UTC, n-merkulova commented on src/components/MainPage/MainPage.tsx
> +                </svg>
Тут отступы поехали(

2021-08-22 20:58 UTC, n-merkulova commented on src/components/RepoCard/RepoCard.css
> +    --colorHint: #7E7E7E;
Если ты используешь эти переменные не только в этом файле, то лучше вынеси их в отдельный файл

2021-08-22 20:58 UTC, n-merkulova commented on src/components/RepoCard/RepoCard.css
> +    padding-top: 23px;
Таким образом ты добиваешься выравнивания правой части карточки по центру по вертикали, как я поняла, а ведь можно (и даже нужно) было просто у repo-card задать свойство align-items: center

2021-08-22 20:58 UTC, n-merkulova commented on src/components/RepoCard/RepoCard.css
> +    display: -webkit-box;
А почему вдруг мы используем вебкит? Чем обычная запись flexbox не подходит?)

2021-08-22 20:58 UTC, n-merkulova commented on src/components/RepoCard/RepoCard.css
> +    font-family: Roboto;
Возможно, удобнее было бы просто добавить шрифт по селектору * на все элементы

2021-08-22 20:58 UTC, n-merkulova commented on src/components/RepoCard/RepoCard.css
> +text-decoration: none;
Опять отступы поехали(

2021-08-22 20:58 UTC, n-merkulova commented on src/components/RepoCard/RepoCard.tsx
> +const baseUrl = 'https://api.github.com/';
Зачем здесь эта переменная?

2021-08-22 20:58 UTC, n-merkulova commented on src/shared/store/ApiStore/ApiStore.ts
> +            response = await fetch(baseUrl + params.endpoint, {
Нужно использовать baseUrl из this. И давай лучше вместо сложения используем шаблонную строку

2021-08-22 20:58 UTC, n-merkulova commented on src/shared/store/ApiStore/ApiStore.ts
> +                data: {} as ErrorT,
Хорошо было бы все же возвращать какую-то ошибку, а не пустой объект. Почему бы не возвращать как раз error, а в дефолтных типах не поменять бы тип {} на тип ошибки?

2021-08-22 20:58 UTC, n-merkulova commented on src/shared/store/ApiStore/ApiStore.ts
> +                method: params.method,
А что насчет других полей из params? Заголовки, например

2021-08-22 20:58 UTC, n-merkulova commented on src/shared/store/ApiStore/ApiStore.ts
> +                status: response?.status || 500,
Это выглядит немного не логично, если честно. Вдруг виноват фронтенд в ошибке, а ты вернешь код статуса 500 и будешь думать, что виноват бэкенд, а на самом деле это не так)))

2021-08-22 20:58 UTC, n-merkulova commented on src/shared/store/ApiStore/ApiStore.ts
> +            success: true,
На данном этапе ты все же не можешь быть уверена, что запрос был успешным, только потому что не выпало исключения. Сейчас у тебя запрос будет успешным, даже если статус ответа не 200, а это неверно

2021-08-22 20:58 UTC, n-merkulova commented on src/shared/store/ApiStore/ApiStore.ts
> +                status: response?.status || 500,
Плюс можно было бы 500 вынести в StatusHTTP, но скорее всего тебе не понадобится это

2021-08-22 20:58 UTC, n-merkulova commented on src/store/GitHubStore/GitHubStore.tsx
> +        const repos = result.data.map((item: { id: any; full_name: string; private: boolean; }) =>
А если в data вернется не массив, упадет ли это?) А еще тип для item можно было бы вынести в файл с типами и назвать, например, ApiRepoItem. И почему в id any, когда number?

2021-08-23 10:42 UTC, FlufyUnicorn commented on src/components/RepoCard/RepoCard.css
> +    display: -webkit-box;
Это нужно для того, чтобы удобно обрезать лишний текст. Если же оставить flexbox, то все будет выглядеть некрасиво

2021-08-23 19:01 UTC, FlufyUnicorn commented on src/shared/store/ApiStore/ApiStore.ts
> +                method: params.method,
В задании было просто потом сказано, что достаточно реализовать fetch для GET запроса, мы же просто будем тягать данные из АПИ. А fetch-у для GET запроса достаточно одного урла, нам же не надо проставлять никакие спец заголовки, типа для CORS или как для POST запросов, мы от них отказались. Иными словами, а зачем нам тогда вообще самим хедеры проставлять?

2021-08-23 19:15 UTC, FlufyUnicorn commented on src/store/GitHubStore/GitHubStore.tsx
> +        const repos = result.data.map((item: { id: any; full_name: string; private: boolean; }) =>
Я просто смотрела документацию, там было показано, что они всегда возвращают массив, проверила запрос на организации где 1 репозиторий, они там всегда отдают массив вне зависимости от того сколько там элементов, так что при данной доке, упасть не должно)

2021-08-29 21:31 UTC, merged